spring:
  banner:
    location: classpath:banner/banner.txt

---
# Development environment
spring:
  config:
    activate:
      on-profile: dev

  banner:
    location: classpath:banner/banner-dev.txt

---
# Staging environment
spring:
  config:
    activate:
      on-profile: stage

  banner:
    location: classpath:banner/banner-stage.txt

---
# Production environment
spring:
  config:
    activate:
      on-profile: prod

  banner:
    location: classpath:banner/banner-prod.txt
