http:
  response:
    json: false
    error:
      page:
        400: error/400
        401: error/401
        402: error/402
        403: error/403
        404: error/404
        405: error/405
        default: error/error
