# Server info
server:
  compression:
    enabled: true
  error:
    include-binding-errors: never
    include-exception: false
    include-message: never
    include-stacktrace: never
    page: /error
    whitelabel:
      enabled: false
  port: 8080
  servlet:
    context-path: '/'
  shutdown: graceful

  tomcat:
    # https://oingdaddy.tistory.com/224
    # Springboot 기동시 Failed to scan : FileNotFoundException *.jar 오류
    additional-tld-skip-patterns: '*.jar'
#    # Tomcat access logs
#    accesslog:
#      enabled: true
#      directory: '${logging.file.path}'
#      max-days: 30
#      pattern: '%h %{X-Forwarded-For}i %l %u [%{yyyy-MM-dd HH:mm:ss}t] "%{Host}i" "%r" %s %b "%{Referer}i" "%{User-Agent}i" TIME:%T'
#      prefix: 'access'
#      suffix: '.log'
#      rotate: true

---
# Development environment
spring:
  config:
    activate:
      on-profile: dev

---
# Staging environment
spring:
  config:
    activate:
      on-profile: stage

---
# Production environment
spring:
  config:
    activate:
      on-profile: prod
