# Spring boot info
spring:
  application:
    name: '@artifactId@'

  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/silver_call
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/H2/silver_call;MODE=MySQL;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:db/schema.sql';
    username: sa
    password:
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5

  # MariaDB로 변경 시 삭제.
  h2:
    console:
      enabled: true
      path: /h2/console

#  config:
#    import:
#      - optional:file:/opt/app-root/etc/conf/application-external.yaml
  profiles:
    group:
      dev: dev
      stage: stage
      prod: prod

  thymeleaf:
    cache: false
#    mode: HTML5

  web:
    resources:
      add-mappings: false

# Mybatis 설정
mybatis:
  config-location: classpath:com/silvercall/persistence/mybatis-config.xml
  mapper-locations: classpath:com/silvercall/persistence/mapper/**/*.xml
  type-aliases-package: com.silvercall.dto.request,silvercall.kt.dto.response,com.silvercall.persistence.model

# Server info
server:
  compression:
    enabled: true
  error:
    include-binding-errors: never
    include-exception: false
    include-message: never
    include-stacktrace: never
    page: /error
    whitelabel:
      enabled: false
  port: 8080
  servlet:
    context-path: '/'
  shutdown: graceful

  tomcat:
    # https://oingdaddy.tistory.com/224
    # Springboot 기동시 Failed to scan : FileNotFoundException *.jar 오류
    additional-tld-skip-patterns: '*.jar'

# Actuator properties
management:
  endpoint:
    env:
      show-values: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - env
          - health
          - info
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  info:
    env:
      enabled: true

# Application info
info:
  app:
    env:          '${spring.profiles.active:@env@}'
    group:        '@groupId@'
    artifact:     '@artifactId@'
    version:      '@version@'
    name:         '@name@'
    description:  '@description@'

---
# Development environment
spring:
  config:
    activate:
      on-profile: dev

---
# Staging environment
spring:
  config:
    activate:
      on-profile: stage

---
# Production environment
spring:
  config:
    activate:
      on-profile: prod

  # If you do not want property defaults to be applied you can set spring.devtools.add-properties to false in your application.properties.
  devtools:
    add-properties: false
    restart:
      enabled: false

decorator:
  datasource:
    p6spy:
      enable-logging: false
