# Spring boot info
spring:
  application:
    name: '@artifactId@'

#  config:
#    import:
#      - optional:file:/opt/app-root/etc/conf/application-external.yaml
  profiles:
    group:
      dev: dev
      stage: stage
      prod: prod

  thymeleaf:
    cache: false
#    mode: HTML5

  web:
    resources:
      add-mappings: false

# Application info
info:
  app:
    env:          '${spring.profiles.active:@env@}'
    group:        '@groupId@'
    artifact:     '@artifactId@'
    version:      '@version@'
    name:         '@name@'
    description:  '@description@'

# Actuator properties
management:
  endpoint:
    env:
      show-values: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - env
          - health
          - info
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  info:
    env:
      enabled: true

# Server info
server:
  compression:
    enabled: true
  error:
    include-binding-errors: never
    include-exception: false
    include-message: never
    include-stacktrace: never
    page: /error
    whitelabel:
      enabled: false
  port: 8080
  servlet:
    context-path: '/'
  shutdown: graceful

  tomcat:
    # https://oingdaddy.tistory.com/224
    # Springboot 기동시 Failed to scan : FileNotFoundException *.jar 오류
    additional-tld-skip-patterns: '*.jar'

---
# Development environment
spring:
  config:
    activate:
      on-profile: dev

---
# Staging environment
spring:
  config:
    activate:
      on-profile: stage

---
# Production environment
spring:
  config:
    activate:
      on-profile: prod

  # If you do not want property defaults to be applied you can set spring.devtools.add-properties to false in your application.properties.
  devtools:
    add-properties: false
    restart:
      enabled: false
