# Spring boot property document : https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
# Setting spring profiles active java option : -Dspring.profiles.active=dev

# How to display auto-configuration report when running a Spring Boot application
# debug: true

# Spring boot info
spring:
  application:
    name: '@artifactId@'

  config:
    import:
      # - classpath:config/banner.yaml
      - classpath:config/http.yaml
      - classpath:config/server.yaml
      - optional:file:/opt/app-root/etc/conf/application-external.yaml
  profiles:
    # active: prod
    group:
      dev: dev
      stage: stage
      prod: prod

#  mvc:
#    view:
#      prefix: '/WEB-INF/views/'
#      suffix: '.jsp'

  thymeleaf:
    cache: false
#    mode: HTML5

  web:
    resources:
      add-mappings: false

# Application info
info:
  app:
    env:          '${spring.profiles.active:@env@}'
    group:        '@groupId@'
    artifact:     '@artifactId@'
    version:      '@version@'
    name:         '@name@'
    description:  '@description@'

# Logging config file
# logging:
#   config: file:/opt/app-root/etc/conf/logback-spring.xml

# Actuator properties
management:
  endpoint:
    env:
      show-values: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - env
          - health
          - info
          - prometheus
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  info:
    env:
      enabled: true

---
# Development environment
spring:
  config:
    activate:
      on-profile: dev

---
# Staging environment
spring:
  config:
    activate:
      on-profile: stage

---
# Production environment
spring:
  config:
    activate:
      on-profile: prod

  # If you do not want property defaults to be applied you can set spring.devtools.add-properties to false in your application.properties.
  devtools:
    add-properties: false
    restart:
      enabled: false

#---
## Kubernetes
#spring:
#  config:
#    activate:
#      on-profile: kubernetes
#    import: "kubernetes:"
#
#  cloud:
#    kubernetes:
#      config:
#        enabled: true
#        sources:
#          - name: '@artifactId@'
